section 4 - blog page
NoroffFEU/musikkforandrerliv.no pull request #222
Opened 2024-03-25 13:39 UTC by LauraBLei

2024-03-27 07:55 UTC, Oyvindeavor approved these changes

2024-03-28 09:08 UTC, Oyvindeavor requested changes
<main> Should only be used once then nest the sections inside it.

2024-03-28 16:57 UTC, LauraBLei commented
Well i cant if im working on them all before the PR have gone through.. cause then there are no main?

2024-03-29 05:39 UTC, Oyvindeavor approved these changes

2024-03-29 05:41 UTC, merged