Adding footer to the pages
NoroffFEU/musikkforandrerliv.no pull request #246
Opened 2024-04-03 09:35 UTC by Iseost

Added footer to the pages that is created. Needs media query and a prfil image

2024-04-03 12:32 UTC, EliNygard requested changes
Double check that the main element is closed before the footer element on all pages.

2024-04-03 12:32 UTC, EliNygard commented on pages/blog.html
>      </main>
Close main before footer

2024-04-03 12:32 UTC, EliNygard commented on pages/support-page.html
>      </main>
Close main before footer

2024-04-04 10:16 UTC, EliNygard commented
Some pages do not have a main tag. Maybe go over with your team and check all pages :)

2024-04-05 11:55 UTC, EliNygard requested changes
Two comments, the rest looks perfect :)

2024-04-05 11:55 UTC, EliNygard commented on pages/gallery-page.html
> +    </main>
I can't find the opening tag for main

2024-04-05 11:55 UTC, EliNygard commented on pages/about-page.html
> +    </main>
I can't find a opening tag for main. No need to close it if the tag is never used.

2024-04-08 08:01 UTC, EliNygard commented
Hi again. Many pages have been updated since this PR and resulted in conflicts on 8 pages. Is it possible for you to create a new PR with a branch that is up to date with main branch?

2024-04-08 08:27 UTC, Iseost commented
I will fix it asap :)

man. 8. apr. 2024 kl. 10:02 skrev Eli Nygård ***@***.***>:

> Hi again. Many pages have been updated since this PR and resulted in
> conflicts on 8 pages. Is it possible for you to create a new PR with a
> branch that is up to date with main branch?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NoroffFEU/musikkforandrerliv.no/pull/246#issuecomment-2042107595>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWP32FRHD3YTONFVZ7OGNILY4JFIDAVCNFSM6AAAAABFU6E2L2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBSGEYDONJZGU>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-04-09 08:08 UTC, EliNygard commented
Great :) What is status? Should we close this PR?

2024-04-09 08:42 UTC, annechh commented
This issue can be closed. There has been opened a new issue for this

2024-04-09 09:11 UTC, EliNygard commented
Wonderful. I will close it.

2024-04-09 09:13 UTC, closed without merging