HTML/CSS section 1 news post page
NoroffFEU/musikkforandrerliv.no pull request #290
Opened 2024-04-05 10:28 UTC by vicwinsj

2024-04-05 11:26 UTC, EliNygard requested changes
I see section 1 has the main tag, not section tag, and that main closes before section 2 starts. Why is that? Main should surround both section 1 and 2.

2024-04-08 16:08 UTC, vicwinsj commented on pages/news-post.html
> +<main class="flex flex-col items-center mx-auto mt-20">
Hi, I just made another commit with the change

2024-04-09 05:59 UTC, EliNygard approved these changes
Great! Thank you :)

2024-04-09 05:59 UTC, EliNygard commented on pages/news-post.html
> +<main class="flex flex-col items-center mx-auto mt-20">
Thank you! I will resolve conflicts and merge :)

2024-04-09 05:59 UTC, merged