media query index
NoroffFEU/musikkforandrerliv.no pull request #396
Opened 2024-04-11 07:53 UTC by Fermain

We have set the max width to 1440.
We have had issues with the header and footer, they need some editing. But due to time constrains we have forcused on what we knew we would be able to finish in time.

2024-04-11 09:38 UTC, EliNygard commented
After a discussion on call we have a solution, waiting for a new push to review.

2024-04-11 09:43 UTC, EliNygard requested changes
Questions from QA we discussed with the assignees:  

- where is the class for media query?
- closing the div

2024-04-11 09:43 UTC, EliNygard commented on index.html
> +    <div class="bg-white flex flex-col items-center">
We can not see that this is being closed.

2024-06-05 14:46 UTC, Fiebie approved these changes

2024-09-27 21:56 UTC, closed without merging